---
title: "Publications"
editor: visual
---
::: {.justify-text}
* **E. Broullón**, P. J. S. Franks, B. Fernández Castro, M. Gilcoto, A. Fuentes-Lema, M. Pérez-Lorenzo, E. Fernández, and B. Mouriño-Carballido. [*Rapid phytoplankton response to wind forcing influences productivity in upwelling bays*](https://doi.org/10.1002/lol2.10309){target="_blank"}. Limnology and Oceanography Letters, 3 2023. ISSN 2378-2242. [doi: 10.1002/lol2.10309](https://doi.org/10.1002/lol2.10309){target="_blank"}.

* **E. Broullón**, P. J. Franks, B. Fernández-Castro, M. Gilcoto, A. Fuentes-Lema, B. Mouriño-Carballido, M. Pérez, and E. Fernández. [*Rapid Fluctuations of the Subsurface Chlorophyll Maximum in Response to Wind Forcing in a Long, Narrow Bay - Supplementary Information*](https://data.mendeley.com/datasets/pm4r2pyyh3/2){target="_blank"}. Mendeley data, 2022.

* B. Fernández Castro, M. Pena, E. Nogueira, M. Gilcoto, **E. Broullón**, A. Comesana, D. Bouffard, A. C. Naveira Garabato, and B. Mouriño-Carballido. [*Intense upper ocean mixing due to large aggregations of spawning fish*](https://doi.org/10.1038/s41561-022-00916-3){target="_blank"}. Nature Geoscience, 15(4):287–292, 4 2022. ISSN 17520908. [doi: 10.1038/s41561-022-00916-3](https://doi.org/10.1038/s41561-022-00916-3){target="_blank"}.

* **E. Broullón**, M. López-Mozos, B. Reguera, P. Chouciño, M. D. Doval, B. Fernández-Castro, M. Gilcoto, E. Nogueira, C. Souto, and B. Mouriño-Carballido. [*Thin layers of phytoplankton and harmful algae
events in a coastal upwelling system*](https://doi.org/10.1016/j.pocean.2020.102449){target="_blank"}. Progress in Oceanography. 189:102449, 2020. ISSN 0079-6611. [doi: 10.1016/J.POCEAN.2020.102449](https://doi.org/10.1016/j.pocean.2020.102449){target="_blank"}.

:::

